# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/jimmylaw21/OneDrive - 南方科技大学/桌面/CPP-main/project4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/jimmylaw21/OneDrive - 南方科技大学/桌面/CPP-main/project4"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jimmylaw21/OneDrive - 南方科技大学/桌面/CPP-main/project4/CMakeFiles" "/mnt/c/Users/jimmylaw21/OneDrive - 南方科技大学/桌面/CPP-main/project4/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/jimmylaw21/OneDrive - 南方科技大学/桌面/CPP-main/project4/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.c

# Build rule for target.
main.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.c
.PHONY : main.c

# fast build rule for target.
main.c/fast:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/build
.PHONY : main.c/fast

mat.o: mat.c.o

.PHONY : mat.o

# target to build an object file
mat.c.o:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/mat.c.o
.PHONY : mat.c.o

mat.i: mat.c.i

.PHONY : mat.i

# target to preprocess a source file
mat.c.i:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/mat.c.i
.PHONY : mat.c.i

mat.s: mat.c.s

.PHONY : mat.s

# target to generate assembly for a file
mat.c.s:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/mat.c.s
.PHONY : mat.c.s

matmul.o: matmul.c.o

.PHONY : matmul.o

# target to build an object file
matmul.c.o:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/matmul.c.o
.PHONY : matmul.c.o

matmul.i: matmul.c.i

.PHONY : matmul.i

# target to preprocess a source file
matmul.c.i:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/matmul.c.i
.PHONY : matmul.c.i

matmul.s: matmul.c.s

.PHONY : matmul.s

# target to generate assembly for a file
matmul.c.s:
	$(MAKE) -f CMakeFiles/main.c.dir/build.make CMakeFiles/main.c.dir/matmul.c.s
.PHONY : matmul.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main.c"
	@echo "... mat.o"
	@echo "... mat.i"
	@echo "... mat.s"
	@echo "... matmul.o"
	@echo "... matmul.i"
	@echo "... matmul.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

